# Generated by Django 4.2.5 on 2023-09-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatspace",
            name="public_id",
            field=models.CharField(
                default="8fBGvg", editable=False, max_length=7, unique=True
            ),
        ),
    ]
