# Generated by Django 4.2.5 on 2023-09-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_chatspace_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatspace",
            name="public_id",
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
    ]
