version: '3'

services:
  database:
    container_name: database
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: password10
      POSTGRES_USER: root
      POSTGRES_DB: socketdb
      POSTGRES_HOST: database
    ports:
      - 5432:5432
    networks:
      - socket-nets

  backend-server:
    container_name: backend-server
    restart: on-failure
    build: .
    env_file:
      - .docker.env
    depends_on:
      - database
    ports:
      - 8000:8000
    networks:
      - socket-nets
    
networks:
  socket-nets:

volumes:
  dbdata:
